package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chapter generated by hbm2java
 */
@Entity
@Table(name = "chapter", catalog = "micro_course")
public class Chapter implements java.io.Serializable {

	private Long chapterId;
	private Course course;
	private String name;
	private String chapbrief;
	private Set<Section> sections = new HashSet<Section>(0);

	public Chapter() {
	}

	public Chapter(Course course, String name) {
		this.course = course;
		this.name = name;
	}

	public Chapter(Course course, String name, Set<Section> sections) {
		this.course = course;
		this.name = name;
		this.sections = sections;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "chapter_id", unique = true, nullable = false)
	public Long getChapterId() {
		return this.chapterId;
	}

	public void setChapterId(Long chapterId) {
		this.chapterId = chapterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chapter")
	public Set<Section> getSections() {
		return this.sections;
	}

	public void setSections(Set<Section> sections) {
		this.sections = sections;
	}
	@Column(name = "chapbrief", nullable = false, length = 100)
	public String getChapbrief() {
		return chapbrief;
	}
	public void setChapbrief(String chapbrief) {
		this.chapbrief = chapbrief;
	}

}
