package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Classify generated by hbm2java
 */
@Entity
@Table(name = "classify", catalog = "micro_course")
public class Classify implements java.io.Serializable {

	private Long classifyId;
	private Orientation orientation;
	private String name;
	private String hrefName;
	private Set<Course> courses = new HashSet<Course>(0);

	public Classify() {
	}

	public Classify(Orientation orientation, String name) {
		this.orientation = orientation;
		this.name = name;
	}

	public Classify(Orientation orientation, String name, Set<Course> courses) {
		this.orientation = orientation;
		this.name = name;
		this.courses = courses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "classify_id", unique = true, nullable = false)
	public Long getClassifyId() {
		return this.classifyId;
	}

	public void setClassifyId(Long classifyId) {
		this.classifyId = classifyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orientation_id", nullable = false)
	public Orientation getOrientation() {
		return this.orientation;
	}

	public void setOrientation(Orientation orientation) {
		this.orientation = orientation;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classify")
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

	public String getHrefName() {
		return hrefName;
	}

	public void setHrefName(String hrefName) {
		this.hrefName = hrefName;
	}

}
