package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Exercise generated by hbm2java
 */
@Entity
@Table(name = "exercise", catalog = "micro_course")
public class Exercise implements java.io.Serializable {

	private Long exerciseId;
	private Section section;
	private String title;
	private String optionA;
	private String optionB;
	private String optionC;
	private String optionD;
	private String name;
	private String answer;
	private String jiexi;

	public Exercise() {
	}

	public Exercise(Section section, String title, String optionA, String optionB, String optionC, String optionD,
			String answer) {
		this.section = section;
		this.title = title;
		this.optionA = optionA;
		this.optionB = optionB;
		this.optionC = optionC;
		this.optionD = optionD;
		this.answer = answer;
	}

	public Exercise(Section section, String title, String optionA, String optionB, String optionC, String optionD,
			String name, String answer) {
		this.section = section;
		this.title = title;
		this.optionA = optionA;
		this.optionB = optionB;
		this.optionC = optionC;
		this.optionD = optionD;
		this.name = name;
		this.answer = answer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "exercise_id", unique = true, nullable = false)
	public Long getExerciseId() {
		return this.exerciseId;
	}

	public void setExerciseId(Long exerciseId) {
		this.exerciseId = exerciseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "section_id", nullable = false)
	public Section getSection() {
		return this.section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	@Column(name = "title", nullable = false, length = 20)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "option_a", nullable = false, length = 20)
	public String getOptionA() {
		return this.optionA;
	}

	public void setOptionA(String optionA) {
		this.optionA = optionA;
	}

	@Column(name = "option_b", nullable = false, length = 20)
	public String getOptionB() {
		return this.optionB;
	}

	public void setOptionB(String optionB) {
		this.optionB = optionB;
	}

	@Column(name = "option_c", nullable = false, length = 20)
	public String getOptionC() {
		return this.optionC;
	}

	public void setOptionC(String optionC) {
		this.optionC = optionC;
	}

	@Column(name = "option_d", nullable = false, length = 20)
	public String getOptionD() {
		return this.optionD;
	}

	public void setOptionD(String optionD) {
		this.optionD = optionD;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "answer", nullable = false, length = 20)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public String getJiexi() {
		return jiexi;
	}

	public void setJiexi(String jiexi) {
		this.jiexi = jiexi;
	}

}
