package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "note", catalog = "micro_course")
public class Note implements java.io.Serializable {

	private Long noteId;
	private Section section;
	private String content;
	private Date postTime;
	private String screenshort;
	private String type; //是否公开
	private String screenshortTime;
	private String videoTime;
	private User user;

	public Note() {
	}

	public Note(Section section, String content, Date postTime) {
		this.section = section;
		this.content = content;
		this.postTime = postTime;
	}

	public Note(Section section, String content, Date postTime, String screenshort) {
		this.section = section;
		this.content = content;
		this.postTime = postTime;
		this.screenshort = screenshort;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "note_id", unique = true, nullable = false)
	public Long getNoteId() {
		return this.noteId;
	}

	public void setNoteId(Long noteId) {
		this.noteId = noteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "section_id", nullable = false)
	public Section getSection() {
		return this.section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	@Column(name = "content", nullable = false, length = 20)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "post_time", length = 18)
	public Date getPostTime() {
		return this.postTime;
	}

	public void setPostTime(Date postTime) {
		this.postTime = postTime;
	}

	@Column(name = "screenshort", length = 16777215)
	public String getScreenshort() {
		return this.screenshort;
	}

	public void setScreenshort(String screenshort) {
		this.screenshort = screenshort;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getScreenshortTime() {
		return screenshortTime;
	}

	public void setScreenshortTime(String screenshortTime) {
		this.screenshortTime = screenshortTime;
	}

	public String getVideoTime() {
		return videoTime;
	}

	public void setVideoTime(String videoTime) {
		this.videoTime = videoTime;
	}

}
