package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ObjectTag generated by hbm2java
 */
@Entity
@Table(name = "object_tag", catalog = "micro_course")
public class ObjectTag implements java.io.Serializable {

	private Long id;
	private Tag tag;
	private Long objectId;
	private long objectType;

	public ObjectTag() {
	}

	public ObjectTag(Tag tag, Long objectId) {
		this.tag = tag;
		this.objectId = objectId;
	}

	public ObjectTag(Tag tag, Long objectId, long objectType) {
		this.tag = tag;
		this.objectId = objectId;
		this.objectType = objectType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tag_id", nullable = false)
	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

	@Column(name = "object_id", nullable = false, length = 20)
	public Long getObjectId() {
		return this.objectId;
	}

	public void setObjectId(Long objectId) {
		this.objectId = objectId;
	}

	@Column(name = "object_type", length = 20)
	public long getObjectType() {
		return this.objectType;
	}

	public void setObjectType(long objectType) {
		this.objectType = objectType;
	}

}
