package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Opus generated by hbm2java
 */
@Entity
@Table(name = "opus", catalog = "micro_course")
public class Opus implements java.io.Serializable {

	private Long opusId;
	private User user;
	private String logo;
	private String sourceCode;
	private String description;
	private int browseCount;
	private Date publishTime;
	private Set<OpusGuide> opusGuides = new HashSet<OpusGuide>(0);

	public Opus() {
	}

	public Opus(int browseCount, Date publishTime) {
		this.browseCount = browseCount;
		this.publishTime = publishTime;
	}

	public Opus(User user, String logo, String sourceCode, String description, int browseCount, Date publishTime,
			Set<OpusGuide> opusGuides) {
		this.user = user;
		this.logo = logo;
		this.sourceCode = sourceCode;
		this.description = description;
		this.browseCount = browseCount;
		this.publishTime = publishTime;
		this.opusGuides = opusGuides;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "opus_id", unique = true, nullable = false)
	public Long getOpusId() {
		return this.opusId;
	}

	public void setOpusId(Long opusId) {
		this.opusId = opusId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "logo", length = 20)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "source_code", length = 20)
	public String getSourceCode() {
		return this.sourceCode;
	}

	public void setSourceCode(String sourceCode) {
		this.sourceCode = sourceCode;
	}

	@Column(name = "description", length = 20)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "browse_count", nullable = false)
	public int getBrowseCount() {
		return this.browseCount;
	}

	public void setBrowseCount(int browseCount) {
		this.browseCount = browseCount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "publish_time", nullable = false, length = 19)
	public Date getPublishTime() {
		return this.publishTime;
	}

	public void setPublishTime(Date publishTime) {
		this.publishTime = publishTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opus")
	public Set<OpusGuide> getOpusGuides() {
		return this.opusGuides;
	}

	public void setOpusGuides(Set<OpusGuide> opusGuides) {
		this.opusGuides = opusGuides;
	}

}
