package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Plan generated by hbm2java
 */
@Entity
@Table(name = "plan", catalog = "micro_course")
public class Plan implements java.io.Serializable {

	private Long planId;
	private String name;
	private String description;
	private String logo;
	private int type;
	private Date createTime;
	private int learnCount;
	private int courseCount;
	private Set<UserPlan> userPlans = new HashSet<UserPlan>(0);
	private Set<Stage> stages = new HashSet<Stage>(0);
	private Set<TagP> tags = new HashSet<TagP>();
	@ManyToMany
	@JoinTable(name="plan_tagP",
			joinColumns={@JoinColumn(name="planId")},
			inverseJoinColumns={@JoinColumn(name="tagId")}
				)
	public Set<TagP> getTags() {
		return tags;
	}

	public void setTags(Set<TagP> tags) {
		this.tags = tags;
	}


	public Plan() {
	}

	public Plan(int type, int learnCount, int courseCount) {
		this.type = type;
		this.learnCount = learnCount;
		this.courseCount = courseCount;
	}

	public Plan(String name, String description, String logo, int type, Date createTime, int learnCount,
			int courseCount, Set<UserPlan> userPlans, Set<Stage> stages) {
		this.name = name;
		this.description = description;
		this.logo = logo;
		this.type = type;
		this.createTime = createTime;
		this.learnCount = learnCount;
		this.courseCount = courseCount;
		this.userPlans = userPlans;
		this.stages = stages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "plan_id", unique = true, nullable = false)
	public Long getPlanId() {
		return this.planId;
	}

	public void setPlanId(Long planId) {
		this.planId = planId;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 20)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "logo", length = 20)
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "learn_count", nullable = false)
	public int getLearnCount() {
		return this.learnCount;
	}

	public void setLearnCount(int learnCount) {
		this.learnCount = learnCount;
	}

	@Column(name = "course_count", nullable = false)
	public int getCourseCount() {
		return this.courseCount;
	}

	public void setCourseCount(int courseCount) {
		this.courseCount = courseCount;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plan")
	public Set<UserPlan> getUserPlans() {
		return this.userPlans;
	}

	public void setUserPlans(Set<UserPlan> userPlans) {
		this.userPlans = userPlans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plan")
	public Set<Stage> getStages() {
		return this.stages;
	}

	public void setStages(Set<Stage> stages) {
		this.stages = stages;
	}

}
