package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Practice generated by hbm2java
 */
@Entity
@Table(name = "practice", catalog = "micro_course")
public class Practice implements java.io.Serializable {

	private Long practiceId;
	private Section section;
	private String target;
	private String description;
	private String result;
	private String task;
	private String name;
	private String initCode;

	public Practice() {
	}

	public Practice(Section section, String target, String description, String result, String task, String name,
			String initCode) {
		this.section = section;
		this.target = target;
		this.description = description;
		this.result = result;
		this.task = task;
		this.name = name;
		this.initCode = initCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "practice_id", unique = true, nullable = false)
	public Long getPracticeId() {
		return this.practiceId;
	}

	public void setPracticeId(Long practiceId) {
		this.practiceId = practiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "section_id")
	public Section getSection() {
		return this.section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	@Column(name = "target", length = 20)
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	@Column(name = "description", length = 20)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "result", length = 18)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "task", length = 20)
	public String getTask() {
		return this.task;
	}

	public void setTask(String task) {
		this.task = task;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "init_code", length = 20)
	public String getInitCode() {
		return this.initCode;
	}

	public void setInitCode(String initCode) {
		this.initCode = initCode;
	}

}
