package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Stage generated by hbm2java
 */
@Entity
@Table(name = "stage", catalog = "micro_course")
public class Stage implements java.io.Serializable {

	private Long stageId;
	private Plan plan;
	private String name;
	private Set<Step> steps = new HashSet<Step>(0);

	public Stage() {
	}

	public Stage(Plan plan, String name) {
		this.plan = plan;
		this.name = name;
	}

	public Stage(Plan plan, String name, Set<Step> steps) {
		this.plan = plan;
		this.name = name;
		this.steps = steps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "stage_id", unique = true, nullable = false)
	public Long getStageId() {
		return this.stageId;
	}

	public void setStageId(Long stageId) {
		this.stageId = stageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plan_id", nullable = false)
	public Plan getPlan() {
		return this.plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stage")
	public Set<Step> getSteps() {
		return this.steps;
	}

	public void setSteps(Set<Step> steps) {
		this.steps = steps;
	}

}
