package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Step generated by hbm2java
 */
@Entity
@Table(name = "step", catalog = "micro_course")
public class Step implements java.io.Serializable {

	private Long stepId;
	private Stage stage;
	private String name;
	private String knowledgePoint;
	private Set<Course> courses = new HashSet<Course>(0);

	public Step() {
	}

	public Step(Stage stage, String name, String knowledgePoint) {
		this.stage = stage;
		this.name = name;
		this.knowledgePoint = knowledgePoint;
	}

	public Step(Stage stage, String name, String knowledgePoint, Set<Course> courses) {
		this.stage = stage;
		this.name = name;
		this.knowledgePoint = knowledgePoint;
		this.courses = courses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "step_id", unique = true, nullable = false)
	public Long getStepId() {
		return this.stepId;
	}

	public void setStepId(Long stepId) {
		this.stepId = stepId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stage_id", nullable = false)
	public Stage getStage() {
		return this.stage;
	}

	public void setStage(Stage stage) {
		this.stage = stage;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "knowledge_point", nullable = false, length = 16777215)
	public String getKnowledgePoint() {
		return this.knowledgePoint;
	}

	public void setKnowledgePoint(String knowledgePoint) {
		this.knowledgePoint = knowledgePoint;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "step_course", catalog = "micro_course", joinColumns = {
			@JoinColumn(name = "step_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "course_id", nullable = false, updatable = false) })
	public Set<Course> getCourses() {
		return this.courses;
	}

	public void setCourses(Set<Course> courses) {
		this.courses = courses;
	}

}
