package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "StudyStatus", catalog = "micro_course")
public class StudyStatus implements java.io.Serializable {

	private Long StudyStId;
	private User user;
	private Course course;
	private int learnedLength;
	private int learnchapterNum;
	private Date startTime;
	@ManyToOne
	@JoinColumn(name="userId")
	public User getUser() {
		return user;
	}
	public void setUser(User user) {
		this.user = user;
	}
	@ManyToOne
	@JoinColumn(name="courseId")
	public Course getCourse() {
		return course;
	}
	public void setCourse(Course course) {
		this.course = course;
	}
	public int getLearnedLength() {
		return learnedLength;
	}
	public void setLearnedLength(int learnedLength) {
		this.learnedLength = learnedLength;
	}
	public int getLearnchapterNum() {
		return learnchapterNum;
	}
	public void setLearnchapterNum(int learnchapterNum) {
		this.learnchapterNum = learnchapterNum;
	}
	public Date getStartTime() {
		return startTime;
	}
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}
	@Id
	@GeneratedValue(strategy = IDENTITY)
	public Long getStudyStId() {
		return StudyStId;
	}
	public void setStudyStId(Long studyStId) {
		StudyStId = studyStId;
	}
	
}
