package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StudyProgressId generated by hbm2java
 */
@Embeddable
public class StudyProgressId implements java.io.Serializable {

	private long userId;
	private long courseId;
	
	public StudyProgressId() {
	}

	public StudyProgressId(long userId, long courseId) {
		this.userId = userId;
		this.courseId = courseId;
	}

	@Column(name = "user_id", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "course_id", nullable = false)
	public long getCourseId() {
		return this.courseId;
	}

	public void setCourseId(long courseId) {
		this.courseId = courseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserCourseId))
			return false;
		UserCourseId castOther = (UserCourseId) other;

		return (this.getUserId() == castOther.getUserId()) && (this.getCourseId() == castOther.getCourseId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUserId();
		result = 37 * result + (int) this.getCourseId();
		return result;
	}

}
