package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserPlan generated by hbm2java
 */
@Entity
@Table(name = "user_plan", catalog = "micro_course")
public class UserPlan implements java.io.Serializable {

	private UserPlanId id;
	private User user;
	private Plan plan;
	private String joinTime;
	private String planCompleteProcess;
    private String learnTime;
    private int learnCount;
    private int rankNum;
	
	
	
	
	
	
	public String getPlanCompleteProcess() {
		return planCompleteProcess;
	}

	public void setPlanCompleteProcess(String planCompleteProcess) {
		this.planCompleteProcess = planCompleteProcess;
	}

	public String getLearnTime() {
		return learnTime;
	}

	public void setLearnTime(String learnTime) {
		this.learnTime = learnTime;
	}

	public int getLearnCount() {
		return learnCount;
	}

	public void setLearnCount(int learnCount) {
		this.learnCount = learnCount;
	}

	public int getRankNum() {
		return rankNum;
	}

	public void setRankNum(int rankNum) {
		this.rankNum = rankNum;
	}

	public UserPlan() {
	}

	public UserPlan(UserPlanId id, User user, Plan plan, String joinTime) {
		this.id = id;
		this.user = user;
		this.plan = plan;
		this.joinTime = joinTime;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false) ),
			@AttributeOverride(name = "planId", column = @Column(name = "plan_id", nullable = false) ) })
	public UserPlanId getId() {
		return this.id;
	}

	public void setId(UserPlanId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plan_id", nullable = false, insertable = false, updatable = false)
	public Plan getPlan() {
		return this.plan;
	}

	public void setPlan(Plan plan) {
		this.plan = plan;
	}

	@Column(name = "join_time", nullable = false, length = 20)
	public String getJoinTime() {
		return this.joinTime;
	}

	public void setJoinTime(String joinTime) {
		this.joinTime = joinTime;
	}

}
