package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserCourse generated by hbm2java
 */
@Entity
@Table(name = "user_course", catalog = "micro_course")
public class UserCourse implements java.io.Serializable {

	private UserCourseId id;
	private User user;
	private Course course;
	private String type;

	public UserCourse() {
	}

	public UserCourse(UserCourseId id, User user, Course course) {
		this.id = id;
		this.user = user;
		this.course = course;
	}

	public UserCourse(UserCourseId id, User user, Course course, String type) {
		this.id = id;
		this.user = user;
		this.course = course;
		this.type = type;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false) ),
			@AttributeOverride(name = "courseId", column = @Column(name = "course_id", nullable = false) ) })
	public UserCourseId getId() {
		return this.id;
	}

	public void setId(UserCourseId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "course_id", nullable = false, insertable = false, updatable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "type", length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
