package com.mc.domain;
// Generated 2015-9-15 12:29:23 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Verify generated by hbm2java
 */
@Entity
@Table(name = "verify", catalog = "micro_course")
public class Verify implements java.io.Serializable {

	private Long verifyId;
	private User user;
	private String selfIntro;
	private String videoDesc;
	private String videoPath;
	private Date submitTime;
	private int status;

	public Verify() {
	}

	public Verify(User user, String selfIntro, String videoDesc, int status) {
		this.user = user;
		this.selfIntro = selfIntro;
		this.videoDesc = videoDesc;
		this.status = status;
	}

	public Verify(User user, String selfIntro, String videoDesc, String videoPath, Date submitTime, int status) {
		this.user = user;
		this.selfIntro = selfIntro;
		this.videoDesc = videoDesc;
		this.videoPath = videoPath;
		this.submitTime = submitTime;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "verify_id", unique = true, nullable = false)
	public Long getVerifyId() {
		return this.verifyId;
	}

	public void setVerifyId(Long verifyId) {
		this.verifyId = verifyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "self_intro", nullable = false, length = 20)
	public String getSelfIntro() {
		return this.selfIntro;
	}

	public void setSelfIntro(String selfIntro) {
		this.selfIntro = selfIntro;
	}

	@Column(name = "video_desc", nullable = false, length = 20)
	public String getVideoDesc() {
		return this.videoDesc;
	}

	public void setVideoDesc(String videoDesc) {
		this.videoDesc = videoDesc;
	}

	@Column(name = "video_path", length = 16777215)
	public String getVideoPath() {
		return this.videoPath;
	}

	public void setVideoPath(String videoPath) {
		this.videoPath = videoPath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "submit_time", length = 19)
	public Date getSubmitTime() {
		return this.submitTime;
	}

	public void setSubmitTime(Date submitTime) {
		this.submitTime = submitTime;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
